// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/Belt_Array.js";
import * as Server from "react-router-mdx/server";
import * as Routes from "@react-router/dev/routes";

let $$default = Belt_Array.concatMany([
  [
    Routes.index("./routes/LandingPageRoute.mjs"),
    Routes.route("syntax-lookup", "./routes/SyntaxLookupRoute.mjs")
  ],
  Server.routes("./routes/MdxRoute.mjs")
]);

export {
  $$default as default,
}
/* default Not a pure module */
