// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/community": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/community";
  };
  "./routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/community/overview.mdx": {
    id: "routes/community/overview";
    page: "/community";
  };
};