// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactRouter from "react-router";
import * as JsxRuntime from "react/jsx-runtime";
import MainCssurl from "../styles/main.css?url";

let mainCss = MainCssurl;

function Root$default(props) {
  return (
    <html lang={"en"}>
      <head>
        <link href={mainCss} rel={"stylesheet"} />
        <ReactRouter.Links />
        <ReactRouter.Meta />
        <meta
          content={"width=device-width, initial-scale=1"}
          name={"viewport"}
        />
        <meta charSet={"UTF-8"} />
        <title>{"ReScript Guide"}</title>
      </head>
      <body>
        <ReactRouter.Outlet />
        <ReactRouter.ScrollRestoration />
        <ReactRouter.Scripts />
      </body>
    </html>
  );
}

let $$default = Root$default;

export { $$default as default };
/* mainCss Not a pure module */
