// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Routes from "@react-router/dev/routes";

let $$default = [Routes.index("./GuideHomeRoute.jsx")];

export {
  $$default as default,
}
/* default Not a pure module */
